config/routes.rb
CreateAndShare::Application.routes.draw do
  root :to => 'posts#index'

  match '/dashboard', to: 'dashboard#index'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/login',  to: 'sessions#new',     :as => :login
  match '/logout', to: 'sessions#destroy', :as => :logout

  get '/start',   to: 'static_pages#start',   :as => :start
  get '/gallery', to: 'static_pages#gallery', :as => :gallery
  get '/faq',     to: 'static_pages#faq',     :as => :faq

  resources :posts
  resources :users, :only => [:create]
  resources :shares, :only => [:create]

  match 'submit' => 'posts#new', :as => :real_submit_path
  match 'mypets' => 'posts#filter', :run => 'my', :as => :mypics
  match ':id' => 'posts#show', :constraints => { :id => /\d+/ }, :as => :show_post
  match ':atype' => 'posts#filter', :constraints => { :atype => /(cat|dog|other)s?/ }, :run => 'animal'
  match ':state' => 'posts#filter', :constraints => { :state => /[A-Z]{2}/ }, :run => 'state'
  match ':atype-:state' => 'posts#filter', :constraints => { :atype => /(cat|dog|other)s?/, :state => /[A-Z]{2}/ }, :run => 'both'
  match 'featured' => 'posts#filter', :run => 'featured', as: :featured
  match 'adopted' => 'posts#filter', :run => 'adopted'
  match 'fix' => 'posts#fix'
  match 'autoimg' => 'posts#autoimg'
  match 'alterimg/:id' => 'posts#alterimg', :as => :alter_image
  match 'flag/:id' => 'posts#flag', :as => :flag
  get 'submit/guide' => 'users#intent', :as => :intent
  match 'sessions' => redirect('/login')
  match ':vanity' => 'posts#vanity', :constraints => { :vanity => /[A-Za-z]+/ }

  match 'auth/:provider/callback' => 'sessions#fboauth'
  match 'auth/failure' => redirect('/'), :notice => 'Login failed! Try again?'

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Services
  include PostsHelper

  # Before everything runs, run an authentication check and an API key check.
  before_filter :is_not_authenticated, :verify_api_key
  skip_before_filter :is_not_authenticated, :only => [:index, :vanity, :show]
  skip_before_filter :is_not_authenticated, :if => Proc.new { |c| params[:action] == 'filter' && params[:run] != 'my' }

  # Ignores xsrf in favor of API keys for JSON requests.
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

  # GET /posts
  # GET /posts.json
  def index
    @admin = ''
    @admin = 'admin-' if admin?

    # Get the page and offset
    page = params[:page] || 0
    offset = (page.to_i * Post.per_page)

    # Basic post query.
    @p = Post
     .joins('LEFT JOIN shares ON shares.post_id = posts.id')
     .select('posts.*, COUNT(shares.*) AS real_share_count')
     .where(:flagged => false)
     .group('posts.id')
     .order('posts.created_at DESC')
     .limit(Post.per_page)
    @sb_promoted = Rails.cache.fetch @admin + 'posts-index-promoted' do
      Post
        .joins('LEFT JOIN shares ON shares.post_id = posts.id')
        .select('posts.*, COUNT(shares.*) AS real_share_count')
        .group('posts.id')
        .where(:promoted => true, :flagged => false)
        .order('RANDOM()')
        .limit(1)
        .all
        .first
    end

    if !params[:last].nil?
      # We're on a "page" of the infinite scroll.  Load the cache for that page.
      @posts = Rails.cache.fetch @admin + 'posts-index-before-' + params[:last] do
      @p
        .where('posts.id < ?', params[:last])
        .where('posts.id != ?', (!@sb_promoted.nil? ? @sb_promoted.id : 0))
        .all
      end
    else
      # We're on the first "page" of the infinite scroll.  Load the cache for
      # promoted, the posts, and the total count.
      @promoted = @sb_promoted
      @posts = Rails.cache.fetch @admin + 'posts-index' do
      @p
        .where(:promoted => false)
        .limit(Post.per_page - 1)
        .all
      end
      @count = Rails.cache.fetch @admin + 'posts-index-count' do
        Post
          .where(:flagged => false)
          .all
          .count
      end
    end

    # The ID of the last post on the page.
    @last = 0
    if !@posts.last.nil?
      @last = @posts.last.id
    end
    # The page.
    @page = page.to_s

    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json { render json: @posts, root: false }
      format.csv { send_data Post.as_csv }
    end
  end

  # GET /(cat|dog|other)s?
  # GET /([A-Z]{2})
  # GET /(cat|dog|other)s?-([A-Z]{2})
  # GET /featured
  # GET /mypics
  def filter
    @admin = ''
    @admin = 'admin-' if admin?

    if params[:atype].is_a? String
      # Cats isn't a valid filter, but cat is.  Let's chop off
      # the "s" if it exists.
      params[:atype] = params[:atype].chop unless params[:atype][-1,1] != 's'
    end

    # Page and offset.
    page = params[:page] || 0
    offset = (page.to_i * Post.per_page)
    @scrolling = !params[:last].nil?

    # Preliminary queries.  These are "finished" later.
    @p = Post
      .joins('LEFT JOIN shares ON shares.post_id = posts.id')
      .select('posts.*, COUNT(shares.*) AS real_share_count')
      .where(:flagged => false)
      .group('posts.id, shares.post_id')
      .limit(Post.per_page)
    @total = Post
      .order('posts.created_at DESC')
      .where(:flagged => false)

    # Sets up all of the filters.
    var = @admin + 'posts-filter-'
    # Animal filters e.g. /cats, /dogs, etc.
    if params[:run] == 'animal'
      var += params[:atype]

      @sb_promoted = Rails.cache.fetch var + '-promoted' do
        @p
          .limit(1)
          .where(:promoted => true, :animal_type => params[:atype])
          .order('RANDOM()')
          .all
          .first
      end

      if !@scrolling
        @promoted = @sb_promoted
      end

      @p = @p
        .where(:animal_type => params[:atype])
        .where('posts.id != ?', (!@sb_promoted.nil? ? @sb_promoted.id : 0))
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total.where(:animal_type => params[:atype]).count
      end
    # State filters e.g. /PA, /NY, /CA, etc.
    elsif params[:run] == 'state'
      var += params[:state]

      @sb_promoted = Rails.cache.fetch var + '-promoted' do
      @p
        .limit(1)
        .where(:promoted => true, :state => params[:state])
        .order('RANDOM()')
        .all
        .first
      end

      if !@scrolling
        @promoted = @sb_promoted
      end

      @p = @p
        .where(:state => params[:state])
        .where('posts.id != ?', (!@sb_promoted.nil? ? @sb_promoted.id : 0))
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total.where(:state => params[:state]).count
      end
    # Combined filters e.g. /cats-NY, /dogs-CA, etc.
    elsif params[:run] == 'both'
      var += params[:atype] + '-' + params[:state]

      @sb_promoted = Rails.cache.fetch var + '-promoted' do
      @p
        .limit(1)
        .where(:promoted => true, :state => params[:state], :animal_type => params[:atype])
        .order('RANDOM()')
        .all
        .first
      end

      if !@scrolling
        @promoted = @sb_promoted
      end

      @p = @p
        .where(:animal_type => params[:atype], :state => params[:state])
        .where('posts.id != ?', (!@promoted.nil? ? @promoted.id : 0))
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total.where(:animal_type => params[:atype], :state => params[:state]).count
      end
    # Featured animals at /featured
    elsif params[:run] == 'featured'
      var += 'featured'
      @p = @p
        .where(:promoted => true)
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total.where(:promoted => true).count
      end
    # Adopted pets at /adopted
    elsif params[:run] == 'adopted'
      var += 'adopted'
      @p = @p
        .where(:adopted => true)
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total.where(:adopted => true).count
      end
    # "My pets" -- pets that I submitted or shared.
    elsif params[:run] == 'my'
      if request.format.symbol == :json && !params[:userid].nil?
        user_id = params[:userid]
      else
        user_id = session[:drupal_user_id]
      end

      var += 'mypets-' + user_id.to_s

      @p = @p
        .where('shares.uid = ? OR posts.uid = ?', user_id, user_id)
        .order('posts.created_at DESC')

      @count = Rails.cache.fetch var + '-count' do
        @total
          .joins('LEFT JOIN shares ON shares.post_id = posts.id')
          .where('shares.uid = ? OR posts.uid = ?', user_id, user_id)
          .count
      end
    end

    # Finish the posts query given the "page" of the infinite scroll.
    if !params[:last].nil?
      @posts = Rails.cache.fetch var + '-before-' + params[:last] do
        @p.where('posts.id < ?', params[:last]).all
      end
    else
      @posts = Rails.cache.fetch var do
        @p
          .offset(offset)
          .limit(Post.per_page - 1)
          .all
      end
    end

    # Basic variables.
    @last = 0
    if !@posts.last.nil?
      @last = @posts.last.id
    end
    @page = page.to_s
    @path = request.fullpath[1..-1]
    @filter = var

    respond_to do |format|
      format.js
      format.html
      format.json { render json: @posts, root: false }
      format.csv { send_data @posts.as_csv }
    end
  end

  # Automatically uploads an image for the form.
  def autoimg
    valid_types = ['image/jpeg', 'image/gif', 'image/png']
    file = params[:file]

    # Make tripl-y sure that we're uploading a valid file.
    if !valid_types.include?(file.content_type)
      render json: { :success => false, :reason => 'Not a valid file.' }
    else
      # Basic variables.
      path = file.tempfile.path()
      name = file.original_filename
      dir = 'public/system/tmp'

      # This shouldn't happen.
      if !File.exists? path
        render json: { :success => false, :reason => "Your file didn't upload properly.  Try again." }
      else
        # Write the file to the tmp directory.
        if File.exists? dir and File.exists? path
          newfile = File.join(dir, name)
          File.open(newfile, 'wb') { |f| f.write(file.tempfile.read()) }
        end
      end

      # Render success.
      render json: { :success => true, :filename => name }
    end
  end

  # GET /alterimg/1
  # Alters image by adding top and bottom text, within semi-transparent block.
  def alterimg
    # We need to be an administrator to be here.
    if !admin?
      redirect_to :root
    end

    # Find the post and the image associated with it.
    @post = Post.find(params[:id])
    image = @post.image.url(:gallery)
    image = '/public' + image.gsub(/\?.*/, '')

    # Rewrite the image.
    if File.exists? Rails.root.to_s + image
      PostsHelper.image_writer(image, @post.meme_text, @post.meme_position)
    end
    
    respond_to do |format|
      format.html { redirect_to show_post_path(@post) }
    end
  end

  # GET /fix
  # Fixes all images should they lose their text.
  def fix
    # Must be an admin to do this.
    if !admin?
      redirect_to :root
    end

    # Get all posts.
    @posts = Post.all
    @posts.each do |post|
      # Get the actual image path.
      image = post.image.url(:gallery)
      image = '/public' + image.gsub(/\?.*/, '')

      # Assuming the file exists, write the text.
      if File.exists? Rails.root.to_s + image
        PostsHelper.image_writer(image, post.meme_text, meme_position)
      end
    end

    respond_to do |format|
      format.html { redirect_to :root, notice: "Images fixed." }
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
  # Finds the break points in a string, given 450px width.  Denotes those breakpoints with '||'
  # @param string text
  #   The string that should be broken.
  def self.find_break_points(text)
    count = position = 0
    text.scan(/./).each do |c|
      count += 1
      position += 1
      if count == 40
        if c == ' '
          text[position] = '||'
        else
          ni = text.index(' ', position - 1)
          ri = text.rindex(' ', position - 1)
          if !ni.nil? && !ri.nil?
            point = [ni, ri].min
          elsif !ri.nil?
            point = ri
          elsif !ni.nil?
            point = ni
          else
            point = 0
          end

          text[point] =  '||'
        end
        count = 1
      end
    end

    text
  end

  # Writes text to an image.
  # @param string path
  #   The path to the image that should have text written on it.
  # @param string meme_text
  #   The text that should be written on the image.
  # @param string meme_position
  #   The position (top or bottom) that the text should be placed on the image.
  def self.image_writer(path, meme_text, meme_position)
  	path = Rails.root.to_s + path
  	path = path.gsub(/\?.*/i, '')

    font_path = Rails.root.to_s + '/DINComp-Medium.ttf'

    the_top_text = the_bottom_text = ''
    if !meme_text.empty?
      if meme_position == 'top'
        the_top_text = meme_text
      elsif meme_position == 'bottom'
        the_bottom_text = meme_text
      end
    end

    # Top text
    if !the_top_text.empty?
      top_text = self.find_break_points(the_top_text)
      top_text = 'Adopt me because...||' + top_text
      top_joined = top_text.split('||')
      top_text = top_joined.join("\n")
      top_height = (top_joined.count * 25) + 10

      # Top text box
      system '''
        convert ''' + path + ''' \
          -strokewidth 0 \
          -fill "rgba( 0, 0, 0 , 0.35 )" \
          -draw "rectangle 0,0 450,''' + top_height.to_s + ''' " \
        ''' + path + '''
      '''

      # Top text
      system '''
        convert ''' + path + ''' \
          -gravity North \
          -font ''' + font_path + ''' \
          -pointsize 25 \
          -size 450x \
          -interline-spacing -13 \
          -fill white \
            -annotate +0-0 "''' + top_text + '''" \
        ''' + path + '''
      '''
    end

    # Bottom text
    if !the_bottom_text.empty?
      bottom_text = self.find_break_points(the_bottom_text)
      bottom_text = 'Adopt me because...||' + bottom_text
      bottom_joined = bottom_text.split('||')
      bottom_text = bottom_joined.join("\n")
      bottom_height = (bottom_joined.count * 25) + 10

      # Bottom text box
      system '''
        convert ''' + path + ''' \
          -strokewidth 0 \
          -fill "rgba( 0, 0, 0 , 0.35 )" \
          -draw "rectangle 450,450 0,''' + (450 - (bottom_height + 6)).to_s + '''" \
        ''' + path + '''
      '''

      # Bottom text
      system '''
        convert ''' + path + ''' \
          -gravity South \
          -font ''' + font_path + ''' \
          -pointsize 25 \
          -size 450x \
          -interline-spacing -13 \
          -fill white \
            -annotate +0-0 "''' + bottom_text + '''" \
        ''' + path + '''
      '''
    end
  end
end

app/views/posts/_cta.html.erb
<section class="cta">
  <div class="section-container">
  	<% if already_submitted? %>
	    <%= link_to :real_submit_path, :class => 'btn btn-large btn-secondary' do %><span>submit another pic</span><% end %>
	    <%= link_to :mypics, :class => 'btn btn-large btn-primary' do %><span>see your pets</span><% end %>
    <% else %>
	    <!--
	    <h1>get involved with your local shelter</h1>
	    -->
      <%= link_to :intent, :class => 'btn btn-large' do %><span>submit your pic</span><% end %>
    <% end %>
  </div>
</section>

app/views/posts/_filter_posts.html.erb
<% cache @admin + @filter + '-page-' + @page do %><% if !@promoted.nil? %><% @post = @promoted %><%= render 'single_post' %><% end %><% @posts.each do |post| %><% @post = post %><%= render 'single_post' %><% end %><% end %>

app/views/posts/_form.html.haml
- content_for(:head) do
  = stylesheet_link_tag 'jquery.Jcrop.min'

%h2 tell us about your animal<
= simple_form_for(@post, :html => { :multipart => true, :class => "form form-submit right" }) do |f|
  - if @post.errors.any? 
    #error_explanation
      %h2 #{pluralize(@post.errors.count, "error")} prohibited this post from being saved:
      %ul#errors
        - @post.errors.full_messages.each do |msg|
          %li= msg

  - if !@post.image_file_name or @post.errors.any? 
    = f.input :image, required: true, wrapper_html: { class: 'form-item-first-name' }, input_html: { accept: 'image/jpeg,image/gif,image/png' } 
    #image-error Invalid file type.
    #allowed-types Your image must be a <strong>.png, .gif or .jpg</strong> file, and be less than <strong>10MB</strong>.

    = f.input :meme_text, required: false, label: "Adopt me because... (optional)", wrapper_html: { class: 'form-item-meme-text', id: 'form-item-meme-text' } 
    = f.input :meme_position, required: false, label: "Text position", wrapper_html: { class: 'form-item-meme-position', id: 'form-item-meme-position' }, :as => :select, :collection => [['Top', 'top'], ['Bottom', 'bottom']], include_blank: false, :selected => 'top' 

    - for attribute in [:crop_x, :crop_y, :crop_w, :crop_h, :crop_dim_w] 
      = f.hidden_field attribute, :id => attribute 

    #upload-preview
      #top_text.text-pos
        Adopt me because...
        .yours
      #placeholder_text
        %span.text Upload an image and it will appear here.
      #bottom_text.text-pos
        Adopt me because...
        .yours
  - else 
    #upload-preview
      = image_tag @post.image.url(:gallery) 

  = f.input :name, required: true, label: "What is the animal's name?", wrapper_html: { class: 'form-item-name' } 
  = f.input :animal_type, required: true, wrapper_html: { class: 'form-item-animal-type' }, :as => :select, :collection => [['Cat', 'cat'], ['Dog', 'dog'], ['Other', 'other']], prompt: 'Choose a type', include_blank: false 
  = f.input :shelter, required: true, label: "What's the name of this animal's shelter?", wrapper_html: { class: 'form-item-shelter' } 
  = f.input :city, required: true, label: "What city is this shelter in?", wrapper_html: { class: 'form-item-city' } 
  = f.input :state, required: true, label: "What state is this shelter in?", wrapper_html: { class: 'form-item-state' }, :as => :select, :collection => get_states.invert, prompt: 'Choose a state', include_blank: false 

  - if admin? 
    = f.input :story, label: "Does this pet have a compelling story? Write it here.", required: false, wrapper_html: { class: 'form-item-story' } 
    = f.input :adopted, label: 'Adopted', :as => :boolean 
    = f.input :flagged, label: 'Flagged', :as => :boolean 
    = f.input :promoted, label: 'Promoted', :as => :boolean 
    = f.input :share_count, label: 'Share count' 

  = f.input :creation_time, :as => :hidden, :value => Time.now 
  = f.input :update_time, :as => :hidden, :value => Time.now 
  = f.submit 'submit', :value => 'Submit', :id => 'edit-final-submit', :class => 'btn primary large' 

app/views/posts/_not_found.html.erb
<section class="posts">
  <div class="section-container">
    <h2>We don't have <%= make_legible %>!</h2>
    <p><%= link_to 'Submit', :real_submit_path %> a photo or try another search above.</p>
  </div>
</section>

app/views/posts/_post.html.erb
<% cache @admin + 'posts-index-page-' + @page do %><% if !@promoted.nil? %><% @post = @promoted %><%= render 'single_post' %><% end %><% @posts.each do |post| %><% @post = post %><%= render 'single_post' %><% end %><% end %>

app/views/posts/_single_post.html.haml
%div{ :class => "post id-#{@post.id}" + (@post.promoted ? ' promoted' : '') + (@post.adopted? ? ' adopted' : '') }
  - if admin?
    .flag-container
      = link_to 'Flag', flag_path(@post), :confirm => 'Flag this?'
      |
      = link_to 'Edit', edit_post_path(@post)
  .share-container
    = link_to('#', :class => 'facebook-share btn share medium', 'data-id' => @post.id) do
      %span Share Me
    %span.share-count= (@post.share_count ? @post.share_count : @post.real_share_count)
  - if @post.promoted
    .promoted-container
      = link_to 'promoted', '/featured', :class => 'promoted-badge'
  - if @post.adopted
    = image_tag '/images/adopted-badge.png', :alt => 'Adopted Pet', :class => 'adopted-badge'
  .image-container
    = image_tag @post.image(:gallery)
  .name-loc
    = link_to show_post_path(@post) do
      <span class="name">#{@post.name}</span>, #{@post.state}
  .story
    =raw simple_format(@post.story).gsub(/(\r|\n|\r\n)/, '')
  .adopt-me
    Adopt #{@post.name} at #{link_to @post.shelter + ', ' + (!@post.city.nil? ? (@post.city + ', ') : '') + @post.state, 'http://www.adoptapet.com/animal-shelter-search?city_or_zip=' + (!@post.city.nil? ? (@post.city + ', ') : '') + @post.state + '&shelter_name=' + @post.shelter + '&distance=50&adopts_out=all', :target => '_blank' }

app/views/posts/edit.html.haml
%section.posts-new
  .section-container
    =render 'form'

app/views/posts/filter.html.erb
<% cache @filter + '-home' do %>
<script type="text/javascript">
<!--
	var count = <%= @count %>;
	var latest = '<%= @last %>';
	var filter = '<%= @path %>';
-->
</script>

<section class="posts">
  <div class="section-container">
    <div class="post-list">
      <% if params[:run] == 'featured' %><h2>These animals needy our help finding a home.  If you can't adopt any, share them with your friends.</h2><% end %>
      <% if @posts.length > 0 %>
        <%=raw render('filter_posts').gsub(/\n/, '') %>
        <div class="inview"></div>
      <% else %>
        <%= render 'not_found' %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/filter.html.haml
- cache @filter + '-home' do
  %script{:type => "text/javascript"}
    var count = #{@count};
    var latest = #{@last};
    var filter = '#{@path}';

  .post-list
    - if @posts.length > 0
      =raw render('filter_posts').gsub(/\n/, '')
      .inview
    - else
      = render 'not_found'

app/views/posts/filter.js.erb
<% if @posts.last.nil? %>
$('.inview').remove();
<% else %>
$('.post-list').append($('<%=raw render('filter_posts').gsub(/(\r|\n|\r\n)/, '').gsub("'", "\\\\'") %>')).append('<div class="inview"></div>'); var latest = <%= @posts.last.id %>; var returned = <%= @posts.length %>;
<% end %>

app/views/posts/index.html.haml
- cache @admin + 'posts-index-home' do
  %script{:type => "text/javascript"}
    var count = #{@count};
    var latest = #{@last};
  
  %section.posts
    .section-container
      %h2 Share shelter pets with friends.
      %p For every 400 shares, we'll donate needed pet supplies to the animal's shelter.
      .post-list
        - if @posts.length > 0
          =raw render('post').gsub(/\n/, '')
          .inview
        - else
          = render 'not_found'

app/views/posts/index.js.erb
<% if @posts.last.nil? %>
$('.inview').remove();
<% else %>
$('.post-list').append($('<%=raw render('post').gsub(/(\n|\r|\r\n)/, '').gsub("'", "\\\\'") %>')).append('<div class="inview"></div>'); var latest = <%= @posts.last.id %>; var returned = <%= @posts.length %>;
<% end %>

app/views/posts/new.html.haml
%section.posts-new
  .section-container
    = render 'form'

app/views/posts/show.html.haml
%section.posts
  .section-container
    %p#notice= notice
    .post-list
      %h2 Help save this animal's life by finding it a home.  If you can't adopt it, share it with a friend.
      = render 'single_post'